// Standalone migration runner. Invoked by `npm run db:migrate`.
//
// Reads SQL files from src/db/migrations/ (generated by `drizzle-kit
// generate`) and applies them in order. Drizzle tracks applied migrations
// in its own __drizzle_migrations table.
//
// Env loaded by `--env-file=.env` in package.json (matches the pattern used
// by `npm run dev` / `npm start` — see comment at top of src/index.js).

import pg from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';

const url = process.env.DATABASE_URL;
if (!url) {
  console.error('[FATAL] DATABASE_URL not set — cannot run migrations.');
  process.exit(1);
}

const pool = new pg.Pool({
  connectionString: url,
  ssl: process.env.PGSSL_DISABLE === 'true'
    ? false
    : (process.env.PGSSL_REJECT_UNAUTHORIZED === 'true'
        ? { rejectUnauthorized: true }
        : { rejectUnauthorized: false }),
});

try {
  const db = drizzle(pool);
  await migrate(db, { migrationsFolder: './src/db/migrations' });
  console.log('[PG] Migrations applied.');
} catch (err) {
  console.error('[PG] Migration failed:', err);
  process.exitCode = 1;
} finally {
  await pool.end();
}
